config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'static_pages/about'

  get 'static_pages/contact'

  root 'static_pages#landing_page'
  # get 'static_pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end

  def landing_page
    @products = Product.limit(3) # number of items in landing_page view
    puts @products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiangue</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/css?family=Lato:200,300,500,700|Grand+Hotel" rel="stylesheet" type="text/css" />

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
          <a class="navbar-brand" href="#">
              <h2>Tiangue</h2>
          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>
        <!-- navbar collapse -->
      </div>
    </nav>
    <div class="wrapper">
      <%= yield %>
    </div>


    <footer>
      <p>&copy; 2016 Nicaragua Tiangue</p>
    </footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :colour %>
    <%= f.text_field :colour%>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
    <div class="product shadow">
        <a href="<%= product_url(product) %>">
            <%= image_tag(product.image_url, class: "img-responsive") %>
            <div class="product-info">
                <h4><%= product.name %></h4>
                <p><%= product.description %></p>
                <strong>
                    $<%= product.price %></strong>
                <p><%= product.colour %></p>
                <p><%=  %></p>
            </div>
        </a>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="main-section">
    <p id="notice"><%= notice %></p>

    <h1>Products</h1>

    <!-- Experimenting with image_tag -->
    <div class="container-fluid">
        <div class="row">
            <%= render @products %> <!-- match the name of the partial, you can shorten this down even further -->
        </div>
    </div>

    <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<h1>About Tiange</h1>
<p>This is the best trade and sell site of all Nicaragua</p>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p>Do you have any question? Drop us a line!</p>

<strong>Phone: </strong><p>(818)555-2332</p>
<strong>Email: </strong><p>tiangue@greenjocote.com</p>
<strong>Address: </strong><p>4321 Hidden St., Los Angeles, CA 91402</p>

app/views/static_pages/index.html.erb
<div class="main-section">
  <h1>Welcome to Bike Berlin</h1>
  <h3>Your source for used bikes in Nicaragua</h3>

    <!-- Experimenting with image_tag -->
    <div class="container-fluid">
        <div class="row">
          <% (1..6).each do |n| %>
            <div class="col-sm-4 col-md-2">
              <%= image_tag("bike#{n}.jpg", class: "img-responsive") %>
            </div>
          <%end%>
        </div>
    </div>

    <%= link_to 'New Product', new_product_path %>
</div>

app/views/static_pages/landing_page.html.erb
<div class="main-section">
  <h1>Featured Products</h1>
  <div class="container-fluid deals-section">
    <div class="row">
      <div class="col-md-8">
        <div id="carousel-example-generic" class="carousel slide">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @products.each_with_index do |_, index| %>
            <li data-target="#carousel-example-generic"  data-slide-to="<%= index %>" class="<%= 'active' if index == 0%>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @products.each do |product| %>
            <div class="item<%= ' active' if product == @products.first %>">
              <div class="row">
                <div class="col-md-7 col-sm-6 col-xs-12 no-padding">
                  <%= image_tag(product.image_url) %>
                </div>
                <div class="col-md-5 col-sm-6 col-xs-12 no-padding">
                  <div class="text-center featured-product-info">
                    <h2><%= product.name %></h2>
                    <div class="card shadow">
                      <p>
                        <%= product.description %>
                      </p>
                      <p>For only
                        <strong><%= " $" + product.price.to_s %></strong>
                      </p>
                      <a href="<%= product_url(product) %>" class="button orange">
                        Buy Now
                      </a>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            <% end %>
            <!-- Slide -->
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="icon-prev"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="icon-next"></span>
          </a>
        </div>
      </div>

      <div class="col-md-4 col-xs-12 col-sm-12">
        <div class="best-deal text-center">
          <h3>Awesome Deal!</h3>
          <%deal = @products.sample%>
          <%= image_tag(deal.image_url, class: "img-responsive") %>
          <div class="best-deal-info">
            <h4><%= deal.name %></h4>
            <p><%= deal.description %></p>
            <p><strong><%= "$" + deal.price.to_s %><strong></p>
            <a href="<%= product_url(deal) %>" class="button orange">
              Buy Now
            </a>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>